### ISSUE TITLE
relax restrictions on log-levels for console handler

### ISSUE THREAD

**Issue by rixmann** [xerions/exlager#23]
I would like to see more relaxed restrictions for the console backend's log-level.

Here they are restricted to `:info` and `:error`
https://github.com/xerions/exlager/blob/master/config/exlager.schema.exs#L25

But i found no explanation why they are restricted, they are not in lager nor in khia/exlager.

Any reason for this? or can it be changed?

**Comment by surik** [comment]
I think there are no reasons for such restrictions. Feel free to extend the schema.
